security:
    encoders:
# Encoders

    role_hierarchy:
# Role hierarchy

    providers:
# Providers

    firewalls:
# Firewalls
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
# Access control