---
roles:
    -   name: symfony
        version: 3.3

security_roles_hierarchy:
    -   parent: admin
        child: moderator
    -   parent: super_admin
        child: admin
    -   parent: moderator
        child: user

security_providers:
    - name: fos_userbundle
      attr_key: id
      attr_value: fos_user.user_provider.username_email

security_access_control:
    - name: '- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }'
    - name: '- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }'
    - name: '- { path: ^/admin/, role: ROLE_ADMIN }'
    - name: '- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }'
    
parameters_clean: []

gitignore: []

parameters:
    locales:
        - { name: 'locale', value: 'en' }
        - { name: 'locales', value: "['%locale%', ru, uk]" }