-   name: Add repository EPEL
    yum:
        name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

#-   name: Install epel-release
#    yum:
#        name: epel-release
#        state: latest
#
#-   name: Install PHP 7.1
#    yum:
#        name: "{{ item }}"
#        state: latest
#    with_items:
#        - php71w
#        - php71w-fpm
#        - php71w-opcache
#    lineinfile:
#        dest: /etc/php-fpm.d/www.conf
#        regexp: '^;listen.owner = .*$'
#        line: "listen.owner = {{ bash_username }}"
#        state: present
#    notify: restart php-fpm

-   name: Fix listen.group for php-fpm
    lineinfile:
        dest: /etc/php-fpm.d/www.conf
        regexp: '^listen.group\s*=.*$'
        line: "listen=/var/run/php-fpm.sock"
        regexp: '^;listen.group = .*$'
        line: "listen.group = {{ bash_username }}"
        state: present
    notify: restart php-fpm
#
#-   name: fix user for php-fpm
#    lineinfile:
#        dest: /etc/php-fpm.d/www.conf
#        regexp: '^user = apache$'
#        line: "user = {{ bash_username }}"
#        state: present
#    notify: restart php-fpm
#
#-   name: fix group for php-fpm
#    lineinfile:
#        dest: /etc/php-fpm.d/www.conf
#        regexp: '^group = apache$'
#        line: "group = {{ bash_username }}"
#        state: present
#    notify: restart php-fpm

-   name: Change listen for php-fpm
    lineinfile:
        dest: /etc/php-fpm.d/www.conf
        regexp: '^listen\s*=.*$'
        line: "listen=/var/run/php-fpm.sock"
        state: present
    notify: restart php-fpm

-   name: Ensure service is started and that it always starts on boot
    service: name=php-fpm state=started enabled=yes
