---
-   name: Run role depends of platform
    include: "{{ item.name }}.yml"
    with_items: "{{ roles }}"
    when: ansible_os_platform|lower == 'redhat'
-   include: debian.yml
    when: ansible_os_platform|lower == 'debian'